//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDoctor
    {
        public tblDoctor()
        {
            this.tblPatients = new HashSet<tblPatient>();
            this.tblVisits = new HashSet<tblVisit>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public Nullable<int> Room { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    
        public virtual ICollection<tblPatient> tblPatients { get; set; }
        public virtual ICollection<tblVisit> tblVisits { get; set; }
    }
}
